<a href="https://colab.research.google.com/github/MariaMalchenko/Machine-Learning/blob/main/%D0%9B%D0%A0_1_%D0%9C%D0%9D_%D1%87%D0%B0%D1%81%D1%822(%D0%B4%D0%BE%D0%B4%D0%B0%D1%82%D0%BA%D0%BE%D0%B2%D0%B5)_%D0%9C%D0%B0%D0%BB%D1%8C%D1%87%D0%B5%D0%BD%D0%BA%D0%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1. вектор з перших 5-ти натуральних чисел

In [2]:
vector = np.array([1, 2, 3, 4, 5])

vector

array([1, 2, 3, 4, 5])

2. транспонований вектор

In [3]:
v1 = np.matrix([1, 2, 3, 4, 5])

print(v1)
v2 = v1.T
v2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

3. Функція, яка повертає вектор у зворотному порядку

In [4]:
v = np.array([1, 2, 3, 4, 5])

print(v[::-1])


[5 4 3 2 1]


4. Середнє значення вектора


In [5]:
print(np.mean(v))

3.0


5. Найбільший і найменший елемент веткора

In [6]:
print(np.max(v))
print(np.min(v))

5
1


6. Скалярний добуток двох векторів

In [8]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

v3 = (np.dot(v1, v2))
print(v3)
print(v1*v2)

32
[ 4 10 18]


7. Функція, яка нормалізує вектор

In [10]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)

print(norm)
v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

8. Два вектори. Визначити, чи є вони ортогональними

In [11]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

np.dot(v1, v2)

np.int64(0)

9. Унікальні елементи вектора

In [12]:
v = np.array([1, 2, 3, 2, 4, 5, 3])

np.unique(v)

array([1, 2, 3, 4, 5])

10. Вектор, що є різницею між двома векторами

In [13]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


11. чи дорівнює довжина вектора 5

In [14]:
vector = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)

np.isclose(length, 5)

np.False_

12. Матриця заповнена випадковими числами

In [15]:
a = np.random.randint(0, 11, (3, 3))
a

array([[2, 5, 2],
       [6, 5, 8],
       [3, 6, 3]])

13. визначник матриці

In [16]:
np.linalg.det(a)


np.float64(6.000000000000003)

14. обернена матриця

In [17]:
np.linalg.inv(a)

array([[-5.50000000e+00, -5.00000000e-01,  5.00000000e+00],
       [ 1.00000000e+00, -6.34413157e-17, -6.66666667e-01],
       [ 3.50000000e+00,  5.00000000e-01, -3.33333333e+00]])


15. система лінійних рівнянь A•x=b, де А - матриця коефіцієнтів, b - вектор вільних членів

In [19]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

x = np.linalg.solve(a, b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


16. множення 2х матриць

In [20]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

np.dot(a, b)

array([-2, -6, 16])

17. транспонвання матриці

In [21]:
print(a.T)
print(b.T)

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


18.  перевірка симетричності матриці

In [22]:
matrix = np.matrix([[2, 2, 2], [2,2,2], [2,2,2]])
np.allclose(matrix, matrix.T)

True

19. обчислення сліду матриці

In [23]:
np.trace(matrix)

np.int64(6)

20. сума матриць

In [25]:
a = np.matrix([[1,2], [3,4]])
b = np.matrix([[5,6], [7,8]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


21. піднесення матриці до ступеня

In [26]:
a = np.matrix([[1,2], [3,4]])

np.linalg.matrix_power(a, 2)

matrix([[ 7, 10],
        [15, 22]])

22. сортування рядків або стопців матриці

In [27]:
b = np.matrix([[5,3,4], [2,3,5], [3,2,3]])

print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [31]:
a = np.array([[1,4],[3,1]])
print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


In [32]:
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[1 1]
 [3 4]]
[[1 4]
 [1 3]]


23. сума елемеентів кожного рядка матриці

In [34]:
row_sums = np.sum(a, axis=1).reshape(-1, 1)

print('сума елементів кожного рядка:\n', row_sums)

сума елементів кожного рядка:
 [[5]
 [4]]
