<a href="https://colab.research.google.com/github/MariaMalchenko/Machine-Learning/blob/main/%D0%9F%D0%A01_%D0%9C%D0%B0%D0%BB%D1%8C%D1%87%D0%B5%D0%BD%D0%BA%D0%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. Матриця 3х3 заповнена випадковими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1,6, size=(3,3))
matrix

array([[2, 2, 5],
       [4, 2, 3],
       [4, 3, 4]])

2. Визначник матриці

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(10.000000000000002)

3. добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
product

np.int64(23040)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(23040)

4. сума всіх елемемнтів матриці

In [ ]:
sum = np.sum(matrix)
sum

np.int64(29)

5. найбільший та найменший елемент

In [ ]:
max_el = np.max(matrix)
print('найбільший елемент', max_el)

min_el = np.min(matrix)
print('найменший елемент', min_el)

найбільший елемент 5
найменший елемент 2


6. середнє значення елементів матриці

In [ ]:
mean_el = np.mean(matrix)
print('середнє значення елементів матриці', mean_el)

середнє значення елементів матриці 3.2222222222222223


7. матриця з квадратних коренів

In [ ]:
sqrt_matrix = np.sqrt(matrix)
print('матриця квадратних коренів:\n', sqrt_matrix)

матриця квадратних коренів:
 [[1.41421356 1.41421356 2.23606798]
 [2.         1.41421356 1.73205081]
 [2.         1.73205081 2.        ]]


8. сума елементів по кожному рядку

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1,1)
print('сума елементів кожного рядка:\n', row_sums)

сума елементів кожного рядка:
 [[ 9]
 [ 9]
 [11]]


9. вектор з 25-ти елементів від 0 до 9. Сортування за спаданням

In [ ]:
vector = np.random.randint(0, 10, size=25)
print('початковий вектор:\n', vector)

sorted_vector = np.sort(vector)[::-1]
print('вектор відсортований за спаданням:\n', sorted_vector)

початковий вектор:
 [9 2 1 6 9 4 2 7 8 7 6 2 5 1 3 1 6 6 0 1 7 8 0 9 0]
вектор відсортований за спаданням:
 [9 9 9 8 8 7 7 7 6 6 6 6 5 4 3 2 2 2 1 1 1 1 0 0 0]


10. мода, медіана, середнє, максимальре, мінімальне значення

In [ ]:
from scipy import stats

mode = stats.mode(vector)

median = np.median(vector)

mean = np.mean(vector)

max_value = np.max(vector)

min_value = np.min(vector)

print('мода', mode)
print('медіана', median)
print('середнє', mean)
print('максимальне значення', max_value)
print('мінімальне значення', min_value)


мода ModeResult(mode=np.int64(1), count=np.int64(4))
медіана 5.0
середнє 4.4
максимальне значення 9
мінімальне значення 0


11. дві матриці 4х4 з числами від 1 до 10. сума, різниця, поелементий добуток, частка

In [ ]:
matrix1 = np.random.randint(1,11, size=(4,4))
matrix2 = np.random.randint(1,11, size=(4,4))

print('матриця 1 \n', matrix1)
print('\nматриця 2 \n', matrix2)

матриця 1 
 [[ 4  9 10  8]
 [ 7  1  1  3]
 [ 7  3  7  7]
 [ 7  2  3  1]]

матриця 2 
 [[ 4  4  4  5]
 [10  8  3  2]
 [ 1  8  9 10]
 [ 5  3  2  6]]


In [ ]:
# сума матриць
matrix_sum = matrix1 + matrix2

# різнция матриць
matrix_diff = matrix1 - matrix2

# добуток матриць
matrix_prod = matrix1 * matrix2

# частка матриць
matrix_division = np.divide(matrix1, matrix2, where =(matrix2!=0))

print('сума матриць\n', matrix_sum)
print('різнция матриць\n', matrix_diff)
print('поелементний добуток\n', matrix_prod)
print('частка матриць\n', matrix_division)

сума матриць
 [[ 8 13 14 13]
 [17  9  4  5]
 [ 8 11 16 17]
 [12  5  5  7]]
різнция матриць
 [[ 0  5  6  3]
 [-3 -7 -2  1]
 [ 6 -5 -2 -3]
 [ 2 -1  1 -5]]
поелементний добуток
 [[16 36 40 40]
 [70  8  3  6]
 [ 7 24 63 70]
 [35  6  6  6]]
частка матриць
 [[1.         2.25       2.5        1.6       ]
 [0.7        0.125      0.33333333 1.5       ]
 [7.         0.375      0.77777778 0.7       ]
 [1.4        0.66666667 1.5        0.16666667]]


12. вектор-рядок з дійсних чисел 1.0-8.0. матриця 3х3. помножити на вектор рядок з 0.0-2.0

In [ ]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3,3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [ ]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])